### ISSUE TITLE
Getting error

### ISSUE THREAD

**Issue by ankur2210** [KiranMohan/bits-wilp#1]
ANKURs-MacBook-Pro:bits-wilp ankurharkawat$ /Users/ankurharkawat/Downloads/bits-wilp/bits-lecture-schedule.sh 
Could not load system_preferences.xml
java.util.prefs.InvalidPreferencesFormatException: org.xml.sax.SAXParseException; lineNumber: 18; columnNumber: 7; The value of attribute "value" associated with an element type "entry" must not contain the '<' character.
    at java.util.prefs.XmlSupport.importPreferences(XmlSupport.java:216)
    at java.util.prefs.Preferences.importPreferences(Preferences.java:1256)
    at org.kiranmohan.bits.wilp.lecture.schedule.LectureSchedule.main(LectureSchedule.java:118)
Caused by: org.xml.sax.SAXParseException; lineNumber: 18; columnNumber: 7; The value of attribute "value" associated with an element type "entry" must not contain the '<' character.
    at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
    at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
    at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:441)
    at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:368)
    at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1437)
    at com.sun.org.apache.xerces.internal.impl.XMLScanner.scanAttributeValue(XMLScanner.java:955)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanAttribute(XMLDocumentFragmentScannerImpl.java:1547)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(XMLDocumentFragmentScannerImpl.java:1319)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2786)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
    at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
    at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
    at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
    at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:243)
    at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:348)
    at java.util.prefs.XmlSupport.loadPrefsDoc(XmlSupport.java:250)
    at java.util.prefs.XmlSupport.importPreferences(XmlSupport.java:199)
    ... 2 more
Connecting to http://vu.bits-pilani.ac.in/onlineLecture/LectSchedule.htm and parsing it.
/var/folders/km/rm9pkd557l719zkd0b_yhln40000gn/T/lecture-schedule-6416365188262719059.html

**Comment by KiranMohan** [comment]
You can download the binary package here https://drive.google.com/open?id=0B-Qi29uJcMn0UmRKT3hnUnRsZFU

The error seems to show that you have edited system_preferences.xml and corrupted it. Please try to validate the xml file with any xml parsing tool.
